easy_admin:
    site_name: Velo Blog
    design:
        brand_color: '#04819e'
        form_theme: 'vertical'
    formats:
        date: 'd.m.Y'
        datetime: 'd.m.Y h:i'
    entities:
        # List the entity class name you want to manage
        Post:
            class: App\Entity\Post
            form:
                fields:
                    - { property: 'tour', label: 'Tour' }
                    - { property: 'title', label: 'Titel' }
                    - { property: 'active', label: 'Aktiviert' }
                    - { property: 'date', label: 'Datum', type_options: { widget: 'single_text' } }
                    - { property: 'headerImageFile', label: 'Header Bild', type: 'file', base_path: '%vich_uploader.mappings%' }
                    - { property: 'text', label: 'Inhalt', type_options: { attr: {'class' : 'form-control tinymce'}} }
                    - { type: 'divider' }
                    - { property: 'gpxFile', label: 'GPX Datei', type: 'file', base_path: '%vich_uploader.mappings%' }
                    - { property: 'distance', label: 'Distanz (km)' }
                    - { property: 'ascent', label: 'Höhenmeter' }
                    - { property: 'descent', label: 'Tiefenmeter' }
                    - { property: 'duration', label: 'Dauer' }
                    - { type: 'divider' }
                    - { property: 'images', label: 'Bilder', type: 'collection', type_options: { entry_type: 'App\Form\ImageType', by_reference: false } }
                    - { type: 'divider' }
            list:
                fields:
                    - { property: 'tour', label: 'Tour' }
                    - { property: 'title', label: 'Titel' }
                    - { property: 'active', label: 'Aktiviert', type: 'toggle' }
                    - { property: 'date', label: 'Datum' }
                    - { property: 'distance', label: 'Distanz (km)' }
                    - { property: 'ascent', label: 'Höhenmeter' }
                actions:
                    - { name: 'show', icon: 'search', label: '' }
                    - { name: 'edit', icon: 'pencil', label: '' }
                    - { name: 'delete', icon: 'trash', label: '' }
        Tour:
            class: App\Entity\Tour
            form:
                fields:
                    - { property: 'title', label: 'Titel' }
                    - { property: 'active', label: 'Aktiviert' }
                    - { property: 'startDate', label: 'Startdatum', type_options: { widget: 'single_text' } }
                    - { property: 'endDate', label: 'Enddatum', type_options: { widget: 'single_text' } }
                    - { type: 'divider' }
                    - { property: 'text', label: 'Inhalt', type_options: { attr: {'class' : 'form-control tinymce'}} }
                    - { type: 'divider' }
                    - { property: 'imageFile', label: 'Bild', type: 'file', base_path: '%vich_uploader.mappings%' }
                    - { type: 'divider' }
            list:
                fields:
                    - { property: 'title', label: 'Titel' }
                    - { property: 'active', label: 'Aktiviert', type: 'toggle' }
                    - { property: 'startDate', label: 'Startdatum' }
                    - { property: 'endDate', label: 'Enddatum' }
                actions:
                    - { name: 'show', icon: 'search', label: '' }
                    - { name: 'edit', icon: 'pencil', label: '' }
                    - { name: 'delete', icon: 'trash', label: '' }
        Media:
            class: App\Entity\Media
            form:
                fields:
                    - { property: 'title', label: 'Titel (optional)' }
                    - { type: 'divider' }
                    - { property: 'file', label: 'Datei', type: 'file', base_path: '%vich_uploader.mappings%' }
                    - { type: 'divider' }
            list:
                fields:
                    - { property: 'title', label: 'Titel' }
                    - { property: 'fileName', label: 'Dateiname', template: 'field_media.html.twig', base_path: '%vich_uploader.mappings%' }
                    - { property: 'fileForPreview', label: 'Vorschau', template: 'field_media_preview.html.twig', base_path: '%vich_uploader.mappings%' }
                actions:
                    - { name: 'show', icon: 'search', label: '' }
                    - { name: 'edit', icon: 'pencil', label: '' }
                    - { name: 'delete', icon: 'trash', label: '' }