vich_uploader:
    db_driver: orm

    mappings:
        post_gpx:
            uri_prefix: /post/gpx
            upload_destination: '%kernel.project_dir%/public/post/gpx'
        post_media:
            uri_prefix: /post/media
            upload_destination: '%kernel.project_dir%/public/post/media'
        post_image:
            uri_prefix: /post/image
            upload_destination: '%kernel.project_dir%/public/post/image'
        tour_image:
            uri_prefix: /tour/image
            upload_destination: '%kernel.project_dir%/public/tour/image'
        media_file:
            uri_prefix: /media
            upload_destination: '%kernel.project_dir%/public/media'